### ISSUE TITLE
All examples give a plain grey screen on iPad pro

### ISSUE THREAD

**Issue by liamwalsh** [sortofsleepy/arkit-tests#24] opened 2017-09-21 10:01 UTC
Running iOS 11 on my iPad Pro 10.5" I don't see any of the camera output on screen
I can see only frame num, frame rate text fields etc - but no camera images, point clouds or planes at all.

**Comment by sortofsleepy** [comment] 2017-09-21 12:54
Hey @liamwalsh !

hmm, that's definitely not right. I have seen this pop up once in awhile the past couple of days and wasn't sure what was causing it as I was never able to consistently reproduce and I thought it was just me experiencing it since no one else with an Ipad pro seems to have noticed this happening. 

Is this a consistent issue? What happens when you restart the app?
Also, just out of curiosity, and because I don't have an iPad to test on, in `ARCam.mm`, what happens when you change line 64 to 
` cameraPlane = ofMesh::plane(ofGetWindowWidth(),ofGetWindowHeight());`
         
was running through it yesterday and that seemed to resolve the issue on my end as far as I could tell.

**Comment by ofZach** [comment] 2017-09-21 15:21
I'm on an ipad 10.5 and I've seen the camera intermittently work and not work.  haven't gotten a great sense of what's causing it.

**Comment by sortofsleepy** [comment] 2017-09-21 15:36
@ofZach oh noooooooo 😢  man - a little more wide spread than I thought then. Was this always a constant thing or did only start to happen the past couple of days? For me I've only seen it happen more recently. 

Yea - I don't haver a terribly good sense of why it's happening either;  I haven't read enough to fully understand what the difference is but now I'm trying to pull the [native bounds of the device](https://developer.apple.com/documentation/uikit/uiscreen/1617810-nativebounds) which should match the stated resolution in the particular iDevice's spec sheet. I can't say for sure but after changing it back to use the oF call and testing a bit later on in the afternoon yesterday that seemed to do the trick . 

will continue to investigate

**Comment by sortofsleepy** [comment] 2017-09-22 03:21
So though it is a bit strange and I'm somewhat worried this'll pop up again haha , but changing that line for me at least, seemed to do the trick and I didn't encounter a gray screen at all during my testing this afternoon across 2 devices. 

will continue to test.

**Comment by sortofsleepy** [comment] 2017-09-22 17:59
AH HA! I think I know what the issue is. There are face up/down events in relation to orientation that I wasn't handling as I didn't think it would really matter, turns out they might be more sensitive then I first thought. 
My guess @liamwalsh is that you're 
* holding your device, with the orientation unlocked
*  at a slight angle with the screen facing upwards, enough for the face up event to register.

Since there's nothing there to handle things, the dimensions being returned to draw the camera image are 0x0. 

Will implement a fix later today.

**Comment by sortofsleepy** [comment] 2017-09-22 22:48
this should now be fixed in `develop`. Trying to work through another issue right now before I merge this into master. Please use `develop` in the meantime. If I don't hear anything back from you over the next couple days, I'm going to close this issue.

**Comment by cindyloo** [comment] 2018-01-07 02:37
hi there - I'm seeing the same gray screen (with frame info) but no camera in the master branch using xcode 9.2, ios11 on an iPhone 6s with 11.2.1. (or any of the simulated devices iphone 8 or less). I'll try with your develop branch and let you know what happens
  
update: haha turns out I don't have a 6s but a 6 - that would be the primary reason for the gray screen. However! - utilizing your 3 newer commits in your develop branch (ofApp.h, ofApp.mm and OFAppViewController.mm) gave me better info - in particular, errors regarding an unsupported configuration. I'd merge those files sooner than later. Thanks for your awesome library!

**Comment by sortofsleepy** [comment] 2018-01-07 03:29
hey @cindyloo !

hmmm... I could have swore I checked out master before the holidays and all appeared well 😓, 
many apologies for the trouble. I will double check things tomorrow and merge in if necessary. 

Some things I'm curious about with your setup in the meantime... 
- From what I understand, the oldest possible device you can have is a 6s( or 6s+). Does the included sample template with XCode work on your 6? There should be a AR project option in the new project wizard of XCode. If you can run that(you shouldn't have to make any changes, it should be good to just go ahead and compile right away), then that means there really is an issue that I need to address.

- Note that the simulator won't work with ARKit due to not having access to your computer's hardware; that being said things may have changed since the last time I tried working with the simulator and I could be totally wrong.

**Comment by cindyloo** [comment] 2018-01-07 03:46
I was able to 'run' the examples on a iphone 6, but locating the problem in the master branch code indicated something other than the configuration  - something along the lines that it couldn't run the planeDetection. Your develop branch updates made the problem more clear - and it's my own fault for thinking I had a 6s versus a 6! 
oh -and a side note- the example Project.xconfig files are defaulting to the iphone 5.1.1 (eg: `IPHONEOS_DEPLOYMENT_TARGET`)and project Document Format to xCode 3-compatible. Maybe you want to update to make easier?
Excited to get my hands on a slightly newer phone and get to it! thanks again

**Comment by sortofsleepy** [comment] 2018-01-08 00:34
@cindyloo

Ah! Gotcha, I misread what you originally wrote before. But thanks for the note about the better error message in develop. 

As far as the Project.xconfig files - that is a auto-generated file from openFrameworks's project generator. Until that gets changed, there's not really anything I can do unfortunately; luckily it should not affect compilation assuming you've changed the actual Xcode project settings.

Also sidenote - if you're gonna get new hardware anyways, might I suggest a 7 at the very least...I have a 6S, it's workable but tracking does seem to bug out quite a bit.

Closing this again.

**Closed as completed by sortofsleepy** 2018-01-08 00:34 UTC
Labels: bug
