### ISSUE TITLE
example-planes fails for 

### ISSUE THREAD

**Issue by kyeshmz** [sortofsleepy/arkit-tests#37] opened 2018-02-17 08:56 UTC
My environment is 
macOS High Sierra 10.13.2
Xcode 9.2
Ipad 12.9 2nd gen
iOs 11.2.5

Getting this error, but I have checked the privacy settings and the plist that we need to do for it to work. Other examples work out fine, but the example planes just doesn't workout.
Any advice where to look?

```
2018-02-17 17:50:05.696577+0900 example-planes[1935:1009465] [Session] Session (0x103f08b10): did fail with error: Error Domain=com.apple.arkit.error Code=102 "Required sensor failed." UserInfo={NSLocalizedRecoverySuggestion=Make sure that the application has the required privacy settings., NSLocalizedDescription=Required sensor failed., NSLocalizedFailureReason=A sensor failed to deliver the required input.}
```

**Comment by sortofsleepy** [comment] 2018-02-17 11:37
hmmmm... this is very strange 😕 . I'm afraid I'm not sure whats happening, this is the first time anyone has reported this. 


1. Quick google seems to suggest the compass might be at fault
https://forums.developer.apple.com/thread/94273

2. On a semi-related note, there's another suggesting that setting the world alignment to something different might fix things 
https://stackoverflow.com/questions/45655562/apple-ios-arkit-a-sensor-failed-to-deliver-the-required-input-error-and-stops

In the example, I'm using an `SFormat` object. Looking at it now I realize I really should have added a getter/setter for it  but you should be able to do something like
```c++
    ARCore::SFormat format;
    format.enablePlaneTracking().enableLighting();
    format.getState().worldAlignment = <alignment type>

    // the options for alignment are -
        // 1. ARWorldAlignmentCamera - https://developer.apple.com/documentation/arkit/arworldalignment/arworldalignmentcamera?language=objc
        // 2. ARWorldAlignmentGravityAndHeading - https://developer.apple.com/documentation/arkit/arworldalignment/arworldalignmentgravityandheading?language=objc
        // 3. ARWorldAlignmentGravity - https://developer.apple.com/documentation/arkit/arworldalignment/arworldalignmentgravity?language=objc
        
```

3. As a test to try and figure out what's going on, Xcode should have a pre-made template for ARKit, have you tried that by any chance to see if that builds and runs? 
Just start a new project, it should be one of the templates.

**Comment by sortofsleepy** [comment] 2018-02-22 16:02
Closing due to lack of an update. If the issue is still there, feel free to re-open! 
Worst worst case, I can just rebuild that example.

**Closed as completed by sortofsleepy** 2018-02-22 16:02 UTC
