### ISSUE TITLE
example-basic adding and removing anchors without input

### ISSUE THREAD

**Issue by aferriss** [sortofsleepy/arkit-tests#30] opened 2017-12-13 23:00 UTC
Even when I comment out all instances of `[session addAnchor:anchor];` and `processor->anchorController->addAnchor();` I get anchors randomly spawning in the scene. The most I've ever seen is 2 at a time, and it seems to occasionally remove the second after some time. Weirdly, I only notice this happening when pointing my device at the floor at around a 45 degree angle.

Seems like after some time `session.currentFrame.anchors.count;` is changing on it's own.

**Comment by sortofsleepy** [comment] 2017-12-13 23:31
hmmmmmmmmmmm... 

I'm inclined to believe it's an ARKit API related on Apple's end for a couple reasons
- `session.currentFrame.anchors.count` is changing (could it be possible that it might be the API just picking up on things automatically like planes?)
- you commented out all the addAnchor calls, that should solve any stray additions outside of automatic ones.

That being said though, it's weird that it only happens when the phone is at a 45 degree angle. 

I've somehow not managed to reproduce this. I have my test device propped up against my monitor at 45 degrees and ran it another 10,000 frames. 

Just to try and see if it is the API picking stuff automatically, I assume the issue doesn't happen once you comment out ?
https://github.com/sortofsleepy/ofxARKit/blob/master/example-basic/src/ofApp.mm#L86

**Comment by sortofsleepy** [comment] 2017-12-13 23:37
Could it be the surface you're pointing the phone at? I think I turned on plane detection by default in all the examples, maybe it's overly textured and ARKit is thinking there's a ton of planes?

**Comment by aferriss** [comment] 2017-12-13 23:55
Well it does still happen with l86 commented out but they're just not being added to the scene. However the anchor count is still finding them.

Yep! It's definitely the planes being detected that are being included in the anchor count. I turned off the plane detection and they stop getting picked up.

Maybe example basic should just use camera mats instead of anchors, since there is already an anchor example. So touchdown could look like

```
void ofApp::touchDown(ofTouchEventArgs &touch){
    matrix_float4x4 coordinateSpaceTransform = matrix_identity_float4x4;
    coordinateSpaceTransform.columns[2].z = -1.0;
    
    matrix_float4x4 newMat = matrix_multiply(session.currentFrame.camera.transform, coordinateSpaceTransform);
    mats.push_back(newMat);
}

```

And then update can have everything removed except `processor->update();`  ?

**Comment by sortofsleepy** [comment] 2017-12-14 00:26
> Well it does still happen with l86 commented out but they're just not being added to the scene. However the anchor count is still finding them.

Right right, that's what I expected would happen, idea was to isolate and make sure it was ARKit adding the anchors itself. 

> Maybe example basic should just use camera mats instead of anchors, since there is already an anchor example. So touchdown could look like...

Hmmm - I don't necessarily have any issues with that idea, I guess I'm worried it'll make things more confusing though for people trying to get a handle on ARKit API if we leave out one of the basic parts of the API in what is supposed to be the very basic example. The other example was more to show how to use AnchorManager class, not necessarily just how to use anchors. 

That being said, you do have a bit of a point, I'll think about that - I do need to clean it up anyways in light of this new discovery(how on earth did I miss this anchor issue early on hahaha 😅 )

**Comment by aferriss** [comment] 2017-12-14 00:50
I suppose I'm a little confused as to the purpose of the anchors actually. Aren't they just an object with an id containing the transform? Seems like the camera transform is just another way to get the same information.

I personally have been using the current frame transform, especially in instances where I want to capture and hold onto a large amount of matrices. For example, if I want to leave a trail of something, it seems like slightly less code to just grab the transforms directly, rather than making a bunch of anchors. 

I only proposed the above because in the example I assume you don't want extraneous planes appearing. I saw this on the docs

>  [Depending on session configuration, ARKit may also add anchors, such as the origin of the world coordinate system or automatically detected planes.](https://developer.apple.com/documentation/arkit/arframe/2867988-anchors?language=objc)

 so if you don't go the current frame transform route, maybe it's worth adding something that would filter out non user added anchors?

Something like what you already have in the anchormanager
```
NSInteger anchorInstanceCount = session.currentFrame.anchors.count;
        
        for (NSInteger index = 0; index < anchorInstanceCount; index++) {
            ARAnchor *anchor = session.currentFrame.anchors[index];
           
            // filter out plane anchors
            if(![anchor isKindOfClass:[ARPlaneAnchor class]]){
                
                
                // Flip Z axis to convert geometry from right handed to left handed
                matrix_float4x4 coordinateSpaceTransform = matrix_identity_float4x4;
                coordinateSpaceTransform.columns[2].z = -1.0;
                
                matrix_float4x4 newMat = matrix_multiply(anchor.transform, coordinateSpaceTransform);
                mats.push_back(newMat);
                
                
                logSIMD(newMat);
                //anchorUniforms->modelMatrix = matrix_multiply(anchor.transform, coordinateSpaceTransform);
            }
        }


```

**Comment by sortofsleepy** [comment] 2017-12-14 04:19
Gagh! On my way home from work I suddenly remembered I actually actually used anchor controller too in the basic example 😓 Sorry to confuse things further, I really do need to clean that up hahaha (man I'm tired). 

Anyways 

> I suppose I'm a little confused as to the purpose of the anchors actually. Aren't they just an object with an id containing the transform? Seems like the camera transform is just another way to get the same information. 

I think you're pretty much right;  but I think also that anchors exist as just using the current transform of the camera is likely a little inflexible depending on what it is you're trying to do. 

> so if you don't go the current frame transform route, maybe it's worth adding something that would filter out non user added anchors?

That's a good point, I could do that ... but in this case I think it'd be easier to just turn off plane detection in this example 😆. I think the built-in point cloud is the only other auto detected thing and that's it's own separate deal.

**Comment by sortofsleepy** [comment] 2017-12-14 19:36
All right - cleaned things up a bit so it should hopefully be more clear. Apologies for making things confusing before, completely forgot I integrated the anchor manager into the example. 

Same basic idea as to what you were thinking, but still thought it was important to at least introduce the idea of anchors.

**Comment by sortofsleepy** [comment] 2017-12-19 04:46
closing since the example has been re-worked. Feel free to re-open if there are more suggestions.

**Closed as completed by sortofsleepy** 2017-12-19 04:46 UTC
